In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import openai

In [14]:
# Set up OpenAI API key
from dotenv import load_dotenv
import os
from pathlib import Path

# Load environment variables from .env file in the project root
env_path = Path("../../.env")  # Adjust path if needed
if env_path.exists():
    load_dotenv(env_path, override=True)
else:
    # Try alternative path
    env_path = Path(".env")
    if env_path.exists():
        load_dotenv(env_path, override=True)

# Initialize OpenAI client with API key
# Option 1: Using environment variable (recommended)
openai_client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Option 2: If you prefer to set it directly (less secure, but simple for testing)
# openai_client = openai.OpenAI(api_key="your-api-key-here")

# Verify the API key is set
if os.getenv("OPENAI_API_KEY"):
    print("✓ OpenAI API key loaded from environment")
else:
    print("⚠ Warning: OPENAI_API_KEY not found in environment variables")
    print("  Make sure your .env file contains: OPENAI_API_KEY=your-key-here")

✓ OpenAI API key loaded from environment

In [114]:



df_rating_sample_2000 = pd.read_json('../../Data/Movies_and_TV.jsonl/Movies_and_TV_ratings_sample_2000.jsonl',lines=True)
df_sample_2000 = pd.read_json('../../Data/sample_2000.jsonl',lines=True)

In [115]:
df_sample_2000

,main_category,title,subtitle,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Prime Video,None,None,4.7,65,None,None,NaN,[{'360w': 'https://m.media-amazon.com/images/G...,[],NaN,None,"{'Content advisory': ['Violence', 'alcohol use...",B01LYA41BY,NaN
1,Prime Video,None,None,4.6,97881,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Content advisory': ['Violence', 'alcohol use...",B00ZHWD78I,NaN
2,Prime Video,None,None,4.9,18911,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Content advisory': ['Violence', 'substance u...",B00U7Q0CXC,NaN
3,Prime Video,None,None,4.6,1346,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Content advisory': ['Violence', 'alcohol use...",B01HUGA1AU,NaN
4,Prime Video,None,None,4.6,114,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Content advisory': ['Violence', 'smoking', '...",B00TE84WCG,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Prime Video,None,None,4.7,637,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Content advisory': ['Nudity', 'violence', 'f...",B000OZNHR4,NaN
1996,Prime Video,None,None,4.9,625,None,None,NaN,[{'360w': 'https://m.media-amazon.com/images/G...,[],NaN,None,"{'Audio languages': ['English'], 'Subtitles': ...",B008RKKSLG,NaN
1997,Prime Video,None,None,4.7,36,None,None,NaN,[{'360w': 'https://m.media-amazon.com/images/G...,[],NaN,None,"{'Audio languages': ['English'], 'Subtitles': ...",B073RPT5CL,NaN
1998,Prime Video,None,None,4.6,13377,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Content advisory': ['Nudity', 'violence', 'a...",B00GIXY4M8,NaN
1999,Prime Video,None,None,4.7,322,None,None,NaN,[{'360w': 'https://images-na.ssl-images-amazon...,[],NaN,None,"{'Audio languages': ['English'], 'Subtitles': ...",B0947GD3J5,NaN

In [117]:
df_rating_sample_2000.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,I'm a sucker for these sappy movies,"I like any movie Hilarie Burton is in, I reall...",[],B07FN83ZK1,B07FN83ZK1,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,2020-10-01 02:00:01.603,0,True
1,5,Funny,I love this show. It is funny and keeps me lau...,[],B0754PSVL2,B0754PSVL2,AFUOYIZBU3MTBOLYKOJE5Z35MBDA,2018-04-27 16:11:35.227,0,False
2,5,Encanto,One of my favorite Disneys to date.. Encanto. ...,[],B0B12GSRKP,B0B12GSRKP,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-11-26 23:08:35.853,0,True
3,5,the hundred foot journey,One of my husband's favorites. He loves stori...,[],B00QGKWI08,B00QGKWI08,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2019-05-18 03:09:12.106,0,True
4,5,Loved this kid-friendly movie,"We loved this movie as a family. Funny, witho...",[],B00ENYKO82,B00ENYKO82,AFMOHJOF54QARPV5DJNPJDN3F4AQ,2013-09-01 00:24:08.000,0,True

In [92]:
list(df_rating_sample_2000["text"].items())[0]
#list(df_rating_sample_2000["title"].items())[0]

(0,
 "I like any movie Hilarie Burton is in, I really like her. This movie is like most  Hallmark movies and they are my guilty pleasure. I liked seeing all the food in the movie and love how the characters come together. I've watched this movie several times and I am sure I'll watch it several more. I like movies that have happy endings and Hallmark certainly is the place to go for that.")

In [119]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['text'])}"

In [120]:

df_rating_sample_2000["description"] = df_rating_sample_2000.apply(preprocess_description, axis=1)

In [121]:
df_rating_sample_2000.head(2)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,description
0,5,I'm a sucker for these sappy movies,"I like any movie Hilarie Burton is in, I reall...",[],B07FN83ZK1,B07FN83ZK1,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,2020-10-01 02:00:01.603,0,True,I'm a sucker for these sappy movies I l i k ...
1,5,Funny,I love this show. It is funny and keeps me lau...,[],B0754PSVL2,B0754PSVL2,AFUOYIZBU3MTBOLYKOJE5Z35MBDA,2018-04-27 16:11:35.227,0,False,Funny I l o v e t h i s s h o w . I t ...

In [113]:
df_rating_sample_2000.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,description
0,5,I'm a sucker for these sappy movies,"I like any movie Hilarie Burton is in, I reall...",[],B07FN83ZK1,B07FN83ZK1,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,2020-10-01 02:00:01.603,0,True,I'm a sucker for these sappy movies I l i k ...
1,5,Funny,I love this show. It is funny and keeps me lau...,[],B0754PSVL2,B0754PSVL2,AFUOYIZBU3MTBOLYKOJE5Z35MBDA,2018-04-27 16:11:35.227,0,False,Funny I l o v e t h i s s h o w . I t ...
2,5,Encanto,One of my favorite Disneys to date.. Encanto. ...,[],B0B12GSRKP,B0B12GSRKP,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-11-26 23:08:35.853,0,True,Encanto O n e o f m y f a v o r i t e ...
3,5,the hundred foot journey,One of my husband's favorites. He loves stori...,[],B00QGKWI08,B00QGKWI08,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2019-05-18 03:09:12.106,0,True,the hundred foot journey O n e o f m y h...
4,5,Loved this kid-friendly movie,"We loved this movie as a family. Funny, witho...",[],B00ENYKO82,B00ENYKO82,AFMOHJOF54QARPV5DJNPJDN3F4AQ,2013-09-01 00:24:08.000,0,True,Loved this kid-friendly movie W e l o v e d ...

In [122]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [ ]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [ ]:

df_rating_sample_2000["description"] = df_rating_sample_2000.apply(preprocess_description, axis=1)

In [97]:
list(df_rating_sample_2000["description"].items())[0]

(0,
 "I'm a sucker for these sappy movies I   l i k e   a n y   m o v i e   H i l a r i e   B u r t o n   i s   i n ,   I   r e a l l y   l i k e   h e r .   T h i s   m o v i e   i s   l i k e   m o s t     H a l l m a r k   m o v i e s   a n d   t h e y   a r e   m y   g u i l t y   p l e a s u r e .   I   l i k e d   s e e i n g   a l l   t h e   f o o d   i n   t h e   m o v i e   a n d   l o v e   h o w   t h e   c h a r a c t e r s   c o m e   t o g e t h e r .   I ' v e   w a t c h e d   t h i s   m o v i e   s e v e r a l   t i m e s   a n d   I   a m   s u r e   I ' l l   w a t c h   i t   s e v e r a l   m o r e .   I   l i k e   m o v i e s   t h a t   h a v e   h a p p y   e n d i n g s   a n d   H a l l m a r k   c e r t a i n l y   i s   t h e   p l a c e   t o   g o   f o r   t h a t .")

In [ ]:
from openai import OpenAI

client = OpenAI(api_key="")

response = client.embeddings.create(
    model="text-embedding-3-small",
    input="Random text",
)

In [20]:
response

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.015960441902279854, -0.0039901104755699635, 0.008389661088585854, 0.0036115716211497784, -0.042859893292188644, -0.0627911314368248, -0.007883654907345772, 0.01200509537011385, -0.013055735267698765, -0.006126152351498604, -0.006767351180315018, 0.011781062930822372, -0.02079647220671177, 0.03779210150241852, 0.02839815430343151, -0.01854068785905838, -0.032044488936662674, -0.006666922476142645, -0.05052337795495987, 0.03371315076947212, -0.015489200130105019, 0.024365555495023727, -0.020178448408842087, 4.9278882215730846e-05, 0.019189612939953804, -0.0015257442137226462, 0.01586773991584778, -0.008714123629033566, 0.036370649933815, -0.036370649933815, 0.024489158764481544, -0.04298349469900131, 0.022418782114982605, -0.025400742888450623, 0.013936417177319527, 0.009108113124966621, 0.05036887153983116, 7.27866863599047e-05, 0.022480584681034088, 0.0022480585612356663, -0.0031654362101107836, -0.04743326082825661, 0.03158097341656685, 0.027532922104001045, 0.03006681613624096, 0.026250524446368217, -0.01988488808274269, -0.0075707812793552876, 0.035474516451358795, 0.061585985124111176, -0.04842209815979004, 0.026744943112134933, 0.0023311052937060595, 0.04823669046163559, -0.005647184792906046, -0.018077170476317406, -0.036803267896175385, 0.04425044357776642, -0.01816987432539463, -0.021862562745809555, 0.02118273638188839, 0.0013664101716130972, -0.01894240267574787, 0.024504609405994415, 0.02972690388560295, 0.004009423777461052, -0.025292588397860527, 0.03519640862941742, 0.016949279233813286, 0.04264358431100845, -0.001063192612491548, -0.005407700780779123, -0.0664992704987526, 0.0003184266679454595, -0.035474516451358795, 0.006323147099465132, 0.0061300150118768215, -0.011332996189594269, 0.005179804749786854, 0.025014478713274002, 0.04125303030014038, 0.03915175423026085, -0.024875422939658165, -0.01815442368388176, -0.0625748261809349, -0.002157286275178194, -0.10815401375293732, -0.007451039273291826, -0.004550193902105093, -0.02384023554623127, -0.024674566462635994, 0.0022326079197227955, -0.043261606246232986, -0.006972071249037981, 0.0007710802019573748, 0.004090539179742336, 0.014052296988666058, 0.03467108681797981, 0.02481362223625183, -0.012700371444225311, 0.014932979829609394, -0.03671056404709816, -0.011363896541297436, 0.0010313257807865739, -0.01872609555721283, 0.0065008290112018585, -0.008760475553572178, -0.033991262316703796, -0.04261268302798271, 0.01832438074052334, -0.0639035701751709, -0.02892347425222397, 0.01875699684023857, -0.005662635434418917, -0.01702653244137764, -0.027579274028539658, 0.043632421642541885, 0.002501061651855707, 0.004048050381243229, -0.03309512883424759, -0.002630460076034069, -0.008443738333880901, 0.019807634875178337, -0.03989338129758835, -0.030035914853215218, -0.036216143518686295, -0.0071149892173707485, -0.023778432980179787, -0.009903817437589169, 0.009417125023901463, 0.047371458262205124, -0.032075390219688416, -0.007215417921543121, -0.011116688139736652, -0.06452159583568573, -0.0047278753481805325, -0.003839467652142048, -0.006218855734914541, -0.05284096300601959, 0.03222989663481712, -0.01343427412211895, -0.013642856851220131, -0.001509327907115221, -0.020719218999147415, -0.001578855561092496, -0.022063419222831726, -0.02099733054637909, -0.012066897936165333, 0.012561316601932049, 0.003182818181812763, -0.04202556237578392, 0.03998608514666557, -0.0548495352268219, 0.02481362223625183, 0.04100582376122475, -0.028058242052793503, 0.03153461962938309, 0.01647031120955944, -0.03633974865078926, -0.018865151330828667, -0.010151026770472527, -0.019776733592152596, 0.005774652119725943, 0.004368649795651436, -0.022403331473469734, -0.011587929911911488, 0.04372512549161911, -8.304683433379978e-05, -0.08695583045482635, 0.01126346830278635, -0.004662210587412119, -0.05305727198719978, -0.05067788064479828, 0.0029800294432789087, -0.02192436344921589, 0.02041020803153515, 0.010629994794726372, -0.011549304239451885, -0.007126577198505402, 0.06325464695692062, 0.038132015615701675, 0.06340915709733963, 0.023423070088028908, -0.0014678045408800244, -0.00453860592097044, -0.05203753337264061, 0.035659924149513245, -0.00553516810759902, 0.003016724484041333, 0.0055158548057079315, -0.026343228295445442, 0.013890066184103489, 0.03048398159444332, -0.004017149098217487, -0.014631693251430988, -0.027100306004285812, 0.054787732660770416, 0.0015238128835335374, -0.013550153002142906, 0.008922706358134747, 0.03238440304994583, 0.05379889905452728, -0.011170764453709126, -0.011703809723258018, -0.046660732477903366, -0.047958582639694214, -0.02574065513908863, 0.013411098159849644, -0.005878943484276533, -0.004511567298322916, 0.11482866108417511, -0.04842209815979004, -0.026914900168776512, -0.048885613679885864, -0.05729072913527489, -0.040944021195173264, 0.04091311991214752, 0.03596893697977066, 0.00964888371527195, -0.02818184718489647, -0.010606818832457066, 0.04187105596065521, 0.060998864471912384, 0.022557837888598442, 0.00023815610620658845, 0.011240292340517044, 0.058341365307569504, -0.0015305724227800965, 0.0004835546715185046, 0.04066590964794159, 0.05657999962568283, 0.005539030767977238, 0.017922665923833847, -0.04143843799829483, 0.059330202639102936, 0.028289999812841415, 0.013001658022403717, 0.004847617354243994, 0.0034860356245189905, 0.030592136085033417, -0.017505500465631485, -0.014454011805355549, 0.03760669752955437, 0.02649773471057415, 0.03766850009560585, -0.03164277598261833, -0.01909690909087658, -0.03652515634894371, 0.045517388731241226, 0.0025126496329903603, 0.028274549171328545, -0.016933828592300415, -0.017335543408989906, -0.003997835796326399, 0.026605887338519096, -0.035690825432538986, -0.0007855651201680303, 0.0276101753115654, 0.03161187469959259, -0.03334233909845352, -0.04434314742684364, -0.044188641011714935, -0.06705549359321594, 0.007230868563055992, -0.005295684095472097, -0.02365482784807682, 0.03028312511742115, -0.015087485313415527, 0.0283518023788929, -0.059515610337257385, -0.014268605038523674, -0.01796901784837246, 0.00562400883063674, 0.031132906675338745, 0.009293519891798496, 0.04480666294693947, -0.016918377950787544, -0.0008913049823604524, -0.02628142572939396, 0.02765652723610401, -0.02102822996675968, 0.01126346830278635, -0.03241530433297157, -0.01985398679971695, -0.024288302287459373, -0.01171926036477089, 0.04409593716263771, 0.005465640686452389, 0.023963840678334236, 0.000375642062863335, -0.01049093995243311, -0.017629103735089302, 0.04211826249957085, -0.019807634875178337, -0.004109852481633425, 0.01630035601556301, 0.027100306004285812, 0.024659115821123123, -0.006578081753104925, 0.013055735267698765, 0.05169761925935745, 0.005736025515943766, 0.013727834448218346, 0.02535439096391201, -0.022573288530111313, 0.03275521472096443, 0.003175092861056328, -0.010807676240801811, 0.027702879160642624, -0.015087485313415527, 0.001119200955145061, 0.03346594423055649, -0.0023987016174942255, -0.009301245212554932, -0.03297152370214462, -0.0328788198530674, 0.013310668990015984, 0.04026419669389725, 0.05883578583598137, -0.07811810076236725, 0.07490438222885132, -0.05481863394379616, 0.06170959025621414, -0.02210977114737034, 0.007798677310347557, -0.013503801077604294, 0.057816047221422195, 0.030035914853215218, 0.052161138504743576, -0.011904667131602764, -0.011580204591155052, -0.03365134820342064, 0.032075390219688416, 0.004978947341442108, 0.05145040899515152, -0.03939896449446678, -0.0146780451759696, 0.032446205615997314, 0.053458984941244125, 0.00026314257411286235, -0.012198228389024734, 0.013642856851220131, 0.002433465328067541, -0.05562206730246544, -0.00954845454543829, -0.05676540732383728, -0.007574643939733505, 0.00439568841829896, -0.02138359472155571, 0.014036846347153187, -0.0033469805493950844, 0.02173895761370659, 0.0179999191313982, -0.06581944227218628, -0.002891188720241189, -0.015002506785094738, 0.020472010597586632, 0.024829072877764702, 0.009540729224681854, 0.015473749488592148, 0.018679743632674217, 0.028259098529815674, 0.018293479457497597, -0.02309860847890377, 0.033960361033678055, 0.01776815950870514, -0.03773030266165733, 0.010073774494230747, 0.009223992936313152, -0.023932939395308495, -0.03519640862941742, 0.028892572969198227, -0.020472010597586632, 0.0013644788414239883, -0.02836725302040577, 0.009733861312270164, -0.020101197063922882, 0.03290972113609314, 0.04211826249957085, 0.037544894963502884, -0.028660815209150314, 0.026142369955778122, -0.030885696411132812, -0.019776733592152596, 0.03593803569674492, 0.02158445119857788, 0.028429055586457253, 0.010336433537304401, -0.04734055697917938, -0.008397386409342289, 0.008830002509057522, 0.021136384457349777, -0.015551002696156502, 0.03507280349731445, 1.3956816928839544e-06, 0.014917529188096523, -0.0038471929728984833, 0.023407619446516037, -0.025215337052941322, -0.004279809072613716, 0.053829800337553024, -0.004337748512625694, -0.03918265551328659, 0.01667116954922676, -0.026760393753647804, 0.019915789365768433, -0.02569430321455002, 0.029077980667352676, 0.04675343632698059, 0.007837303914129734, 0.0404496006667614, -0.014438561163842678, 0.03445477783679962, 0.009208542294800282, -0.01494070515036583, 0.009610257111489773, 0.07743827253580093, 0.006751900538802147, 0.000569739902857691, 0.05052337795495987, -0.028892572969198227, -0.021862562745809555, -0.037761203944683075, -0.02365482784807682, -0.011255742982029915, 0.05574566870927811, 0.050461575388908386, -0.038348324596881866, -0.016192201524972916, -0.02968055196106434, -0.0008299854816868901, -0.02329946495592594, -0.016145849600434303, -0.0036212282720953226, 0.029047079384326935, -0.010753598995506763, -0.01985398679971695, 0.030947498977184296, -0.011757886968553066, -0.03902814909815788, -0.014531265012919903, 0.024149246513843536, -0.07070182263851166, 0.008729574270546436, -0.02722391113638878, 0.018865151330828667, 0.01739734597504139, 0.013866890221834183, -0.035845331847667694, -0.0450538732111454, -0.012723547406494617, -0.025508897379040718, -0.006539455149322748, -0.040789514780044556, 0.03337324038147926, -0.03346594423055649, 0.03912085294723511, 0.013550153002142906, -0.0022480585612356663, 0.026157820597290993, 0.015635980293154716, -0.029865959659218788, -0.028645364567637444, 0.0011037503136321902, 0.028877122327685356, -0.06041174381971359, -0.0072385938838124275, 0.0428289920091629, 0.0428289920091629, -0.006388812325894833, -0.015442848205566406, 0.012028271332383156, 0.008304683491587639, 0.025477996096014977, 0.006184092257171869, -0.027146657928824425, 0.02951059490442276, -0.06220401078462601, -0.011139864102005959, 0.024458257481455803, 0.03216809406876564, 0.00317123020067811, 0.013117536902427673, 0.0024296026676893234, -0.016964729875326157, 0.0856579840183258, -0.007640308700501919, 0.02234152890741825, 0.015157013200223446, -0.011124413460493088, -0.03153461962938309, 0.020178448408842087, 0.02989686094224453, -0.019452271983027458, 0.03145736828446388, -0.031472817063331604, -0.014585341326892376, -0.03229169920086861, -0.01098535768687725, -0.0653868317604065, -0.0119123924523592, 0.0036791679449379444, -0.019544975832104683, 0.02215612307190895, 0.02666768990457058, 0.019452271983027458, 0.012731272727251053, 0.0029838921036571264, 0.00309977144934237, 0.028150945901870728, 0.016563015058636665, 0.0004219937836751342, 0.005249332636594772, -0.016887476667761803, -0.007667347323149443, 0.008976783603429794, -0.013828263618052006, -0.006748037878423929, -0.01059909351170063, -0.046629831194877625, 0.03238440304994583, 0.03011316806077957, 0.012885778211057186, -0.014639418572187424, 0.005952333565801382, -0.05107959732413292, -0.036061640828847885, -0.02345397137105465, -0.0028467681258916855, 0.008119276724755764, 0.01050639059394598, 0.008466914296150208, 0.07508978992700577, 0.016192201524972916, -0.002821661066263914, -0.03714317828416824, -0.006048899609595537, 0.004944183398038149, 0.03800841048359871, 0.005608558189123869, 0.012429986149072647, 0.041160330176353455, 0.04264358431100845, -0.012599943205714226, -0.04561009258031845, 0.026636788621544838, 0.014075472950935364, -0.003671442624181509, 0.0018241333309561014, -0.010807676240801811, 0.020487461239099503, -0.004639034625142813, -0.001702460111118853, -0.01776815950870514, 0.034176670014858246, -0.00935532245784998, -0.001266947016119957, 0.02384023554623127, 0.032260797917842865, 0.013689208775758743, 0.010398236103355885, 0.0008309511467814445, -0.0006045036716386676, 0.007400824688374996, -0.015929540619254112, 0.01032098289579153, -0.02499902807176113, 0.044559456408023834, 0.03705047443509102, -0.028320901095867157, 0.0200393944978714, 0.017258290201425552, 0.0033720876090228558, -0.03156552091240883, -0.01068407204002142, -0.002502992982044816, 0.03253890946507454, -0.0053072720766067505, -0.025864260271191597, 0.01911235973238945, -0.007084087934345007, 0.03349684551358223, 0.028444506227970123, 0.027671977877616882, -0.04922552779316902, 0.034918297082185745, 0.007555330637842417, -0.018030820414423943, 0.0033856069203466177, 0.0039012697525322437, 0.04582640156149864, 0.024288302287459373, -0.0027038503903895617, 0.03612343966960907, 0.0006083663320168853, 0.009849741123616695, -0.014708946458995342, -0.03803931176662445, -0.035690825432538986, -0.0015209158882498741, 0.03365134820342064, -0.004426589235663414, -0.005195255391299725, -0.015164738520979881, 0.021352693438529968, 0.01645486056804657, -0.009896092116832733, -0.017520951107144356, 0.014809374697506428, -0.043941430747509, -0.007203829940408468, 0.014253154397010803, 0.006755763199180365, -0.015767309814691544, -0.020193899050354958, 0.006798252463340759, -0.03306422755122185, -0.010568192228674889, 0.008613694459199905, 0.018015369772911072, -0.029649650678038597, 0.002101277932524681, 0.04029509797692299, -0.008675497025251389, -0.03936806321144104, 0.002423808677121997, -0.015249716117978096, -0.021136384457349777, 0.014593066647648811, -0.00916219037026167, 0.006323147099465132, -0.0011810031719505787, -0.0006016067345626652, -0.020178448408842087, -0.008374211378395557, -0.010931281372904778, 0.02232607826590538, 0.00907721184194088, 0.01175016164779663, -0.025632502511143684, 0.03164277598261833, -0.009617982432246208, 0.01391324121505022, -0.028274549171328545, 0.04425044357776642, -0.009131289087235928, 0.022619640454649925, 0.015836838632822037, 0.011765612289309502, -0.03875003755092621, -0.016532113775610924, -0.002547413343563676, 0.004967359360307455, -0.014824825339019299, -0.008644595742225647, -0.021986166015267372, -0.005944608245044947, -0.02348487265408039, -0.004476803820580244, -0.028073692694306374, -0.006898681167513132, -0.019158711656928062, -0.015303793363273144, -0.007165203802287579, -0.036957770586013794, 0.04536288604140282, -0.02873806655406952, -0.026961252093315125, -0.014438561163842678, 0.02385568618774414, 0.0011172696249559522, 0.03145736828446388, -0.0011336858151480556, -0.008096100762486458, 0.02121363766491413, 0.013866890221834183, 0.0049750846810638905, -0.04598090797662735, 0.010568192228674889, -0.008474639616906643, 0.01427633035928011, 0.010545016266405582, -0.020317504182457924, -0.01668662019073963, -0.0238247849047184, 0.03386765718460083, 0.02628142572939396, 0.018278028815984726, -0.032817017287015915, -0.015041133388876915, -0.04561009258031845, -0.026389580219984055, 0.04650622606277466, 0.02286684885621071, 0.02059561386704445, -0.009478926658630371, 0.006072075571864843, 0.0255706999450922, -0.029649650678038597, -0.03689597174525261, 0.012484063394367695, 0.017922665923833847, -0.02102822996675968, 0.015072034671902657, 0.01570550911128521, -0.04103672504425049, 0.02141449600458145, -0.021646253764629364, 0.02173895761370659, 0.0008966160821728408, 0.00047510513104498386, -0.008660046383738518, -0.013248867355287075, -0.002754064742475748, -0.02311405912041664, 0.018061719834804535, 0.009115838445723057, -0.02632777765393257, -0.008490090258419514, -0.005654910113662481, 0.011039434932172298, 0.03315693140029907, 0.015025682747364044, -0.01586773991584778, -0.023191310465335846, -0.03476379066705704, 0.02594151347875595, -0.03315693140029907, -0.0030283124651759863, 0.0522538386285305, 0.006817565765231848, 0.011417973786592484, 0.04428134486079216, -0.02042565867304802, 0.00113465148024261, -0.0018279959913343191, -0.01155702956020832, -0.017675455659627914, 0.0016773529350757599, -0.004866930656135082, 0.0003056316636502743, -0.0048167165368795395, 0.006516279652714729, 0.02535439096391201, -0.01059909351170063, 0.014067747630178928, 0.03705047443509102, -0.0003553631831891835, -0.01068407204002142, -0.0033334612380713224, -0.04938003420829773, 0.01429178100079298, -0.0217853095382452, -0.01724283955991268, -0.009733861312270164, -0.03467108681797981, 0.04199466109275818, 0.0010303601156920195, 0.014461737126111984, 0.07335932552814484, -0.0032484831754118204, 0.04242727532982826, -0.0026478420477360487, 0.03646335378289223, -0.04347791522741318, -0.025601601228117943, -0.008165628649294376, 0.005384524818509817, -0.014392209239304066, 0.013496075756847858, 0.013125262223184109, -0.007690523285418749, -0.015442848205566406, 0.010042873211205006, 0.012793075293302536, -0.017072884365916252, -0.05843406915664673, 0.03973887488245964, -0.005720574874430895, -0.023932939395308495, -0.007736874744296074, 0.01648576185107231, -0.032847918570041656, 0.021522648632526398, -0.00833558477461338, -0.016393058001995087, 0.036803267896175385, 0.015211089514195919, 0.00577851478010416, -0.004179380368441343, 0.008196529000997543, -0.05852677300572395, 0.030962949618697166, -0.024442806839942932, -0.024921774864196777, 0.015759585425257683, -0.006581944413483143, -0.08009577542543411, 0.018123522400856018, -0.002698056399822235, 0.021460846066474915, -0.0053072720766067505, 0.0019767077174037695, 0.04010969027876854, 0.030329477041959763, -0.005450190044939518, -0.024674566462635994, 0.039244458079338074, -0.020178448408842087, -0.020023943856358528, -0.004434314556419849, 0.013496075756847858, -0.011587929911911488, 0.012746723368763924, -0.021893462166190147, -0.04054230451583862, -0.022758694365620613, -0.02822819910943508, -0.007702110800892115, 0.03596893697977066, -0.013573328964412212, -0.022187024354934692, -0.010575917549431324, -0.005940745584666729, 0.030901147052645683, 0.0065742190927267075, -0.014616242609918118, 0.047371458262205124, 0.0037062063347548246, 0.017629103735089302, -0.019004205241799355, -0.0008309511467814445, -0.04211826249957085, -0.01351152639836073, 0.00011129241465823725, 0.024180147796869278, -0.01568233221769333, -0.016933828592300415, -0.0359998382627964, -0.002922089770436287, 0.02934063971042633, -0.016732972115278244, 0.00431070988997817, 0.002742476761341095, 0.003839467652142048, -0.03426937386393547, -0.02102822996675968, -0.0018241333309561014, -0.0003819188568741083, 0.041747450828552246, -0.02424195036292076, -0.01239908579736948, 0.04647532477974892, -0.05318087339401245, -0.004828304518014193, -0.009849741123616695, -0.002825523726642132, 0.01667116954922676, -0.0016763872699812055, 0.0003478793369140476, 0.017690906301140785, 0.023191310465335846, -0.031673677265644073, -0.006968208588659763, 0.023314915597438812, 0.03141101822257042, -0.004453627858310938, -0.02155354991555214, 0.02858356200158596, -0.011325270868837833, 0.022418782114982605, 0.006755763199180365, -0.040944021195173264, 0.03939896449446678, 0.016578465700149536, 0.021831661462783813, -0.042272768914699554, 0.04202556237578392, -0.0030785268172621727, -0.008188803680241108, 0.012352733872830868, 0.0014900147216394544, -0.01446946244686842, 0.028846221044659615, -0.01259221788495779, -0.04635171964764595, 0.009849741123616695, 0.049472738057374954, -0.00581714091822505, -0.0030495570972561836, -0.012175052426755428, -0.00860596913844347, -0.019004205241799355, -0.01039051078259945, 0.015527826733887196, -0.0009265515836887062, -0.016516663134098053, 0.0

In [19]:
type(response)

openai.types.create_embedding_response.CreateEmbeddingResponse

In [21]:
len(response.data[0].embedding)

1536

In [143]:
def get_embedding(text, model="text-embedding-3-small"):
    # Use the openai_client instance created in Cell 1
    response = openai_client.embeddings.create(
        input=text,
        model=model,
    )
    return response.data[0].embedding

In [ ]:
get_embedding("Hello, world!")

In [106]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [ ]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-00",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

Create pointstruct to structure the embedded vectors for loading into quadrant collection

In [108]:
pointstruct = PointStruct(
    id=0,
    vector=get_embedding("Test text"),
    payload={
        "text": "Test text",
        "model": "text-embedding-3-small",
    },
)

In [128]:
data_to_embed = df_rating_sample_2000[["description","rating","asin","parent_asin"]].to_dict(orient="records")

In [137]:
data_to_embed_dev = data_to_embed[0:9]

In [139]:
data_to_embed_dev

[{'description': "I'm a sucker for these sappy movies I   l i k e   a n y   m o v i e   H i l a r i e   B u r t o n   i s   i n ,   I   r e a l l y   l i k e   h e r .   T h i s   m o v i e   i s   l i k e   m o s t     H a l l m a r k   m o v i e s   a n d   t h e y   a r e   m y   g u i l t y   p l e a s u r e .   I   l i k e d   s e e i n g   a l l   t h e   f o o d   i n   t h e   m o v i e   a n d   l o v e   h o w   t h e   c h a r a c t e r s   c o m e   t o g e t h e r .   I ' v e   w a t c h e d   t h i s   m o v i e   s e v e r a l   t i m e s   a n d   I   a m   s u r e   I ' l l   w a t c h   i t   s e v e r a l   m o r e .   I   l i k e   m o v i e s   t h a t   h a v e   h a p p y   e n d i n g s   a n d   H a l l m a r k   c e r t a i n l y   i s   t h e   p l a c e   t o   g o   f o r   t h a t .",
  'rating': 5,
  'asin': 'B07FN83ZK1',
  'parent_asin': 'B07FN83ZK1'},
 {'description': 'Funny I   l o v e   t h i s   s h o w .   I t   i s   f u n n y   a n d   k e e p s   m e   l a u g h i n g .',
  'rating': 5,
  'asin': 'B0754PSVL2',
  'parent_asin': 'B0754PSVL2'},
 {'description': "Encanto O n e   o f   m y   f a v o r i t e   D i s n e y s   t o   d a t e . .   E n c a n t o .     I f   y o u   l i k e d   C o c o ,   t r y   i t .     A   g r e a t   s t o r y   a n d   a w e s o m e   m u s i c .   H a v i n g   s a i d   a l l   o f   t h i s ,   I   n e v e r   h e s i t a t e   t o   u p d a t e   m y   r e v i e w s   s h o u l d   n e w   i n f o   s e e m   u s e f u l .   A l l   o f   m y   r e v i e w s   r e f l e c t   m y   h o n e s t ,   p e r s o n a l   e x p e r i e n c e   w i t h   t h e   r e v i e w e d   i t e m   -   y o u r   e x p e r i e n c e   m a y   b e   d i f f e r e n t .   I   a m   n o t   i n f l u e n c e d   b y   a n y   o u t s i d e   s o u r c e .   I   r e c e i v e / a c c e p t   N O   f r e e   p r o d u c t s   o r   d i s c o u n t s   t h a t   a r e   n o t   a v a i l a b l e   t o   a l l   s h o p p e r s -   e v e r .   F o r   s o m e   r e a s o n   o u r   s h o p p e r   r a n k s   a r e   n o   l o n g e r   v i s i b l e   -   s o ,   t o   g i v e   y o u   a   l i t t l e   m o r e   i n f o   a b o u t   m e ,   I   a m   a   t o p   5 0   r e v i e w e r   ( # 3 0   t h e   h i g h e s t   r a n k   a c h i e v e d ) .   T h o s e   n u m b e r s   u s e d   t o   f l u c t u a t e   o v e r   t i m e   -   u p   a n d   d o w n   b u t   I   n o t i c e d   t h a t   t h e y   s t o p p e d   u p d a t i n g   r e g u l a r l y   -   p e r h a p s   t o   p h a s e   t h e m   o u t . \xa0   I ' v e   b e e n   d o i n g   r e v i e w s   f o r   o v e r   2 5   y e a r s   w i t h   A m a z o n   -   n e a r l y   6 , 0 0 0   r e v i e w s   p o s t e d ,   v i e w e d   o v e r   5 0 , 0 0 0   t i m e s ,   a n d   o v e r   2 4 , 0 0 0   l i k e s .",
  'rating': 5,
  'asin': 'B0B12GSRKP',
  'parent_asin': 'B0B12GSRKP'},
 {'description': "the hundred foot journey O n e   o f   m y   h u s b a n d ' s   f a v o r i t e s .     H e   l o v e s   s t o r i e s   t h a t   i n v o l v e   C h e f s .     H a h a h a . . .   i t   i s   a   c l a s s i c   I   h a t e   y o u .   . .   b u t   w a i t . . .   n o   I   d o n ' t .     I t   i s   n o t   a   t e r r i b l y   c o m p l i c a t e d   s t o r y ,   b u t   w e l l   t o l d   a n d   f i l m e d .     I   l o v e   t h e   F r e n c h   a c c e n t s   -   i t ' s   r o m a n t i c .     A n   I n d i a n   f a m i l y ,   l o o k i n g   f o r   a   p l a c e   t o   l a n d   a n d   h a v e   r e s t a u r a n t   f i n d   a   p l a c e   d i r e c t l y   a c r o s s   t h e   s t r e e t   ( a   h u n d r e d   f e e t   -   g e t   i t ? )   f r o m   a   f r o s t y   o l d   w o m a n   r e s t a u r a t e u r .     T h e   c o m p e t i t i o n   b e g i n s .     T h e y   t r a d e   t i t   f o r   t a t . . .   a n d   t h e   s t o r y   e v o l v e s . .   w i t h o u t   g i v i n g   i t   a l l   a w a y ,   a l l s   w e l l   t h a t   e n d s   w e l l .     I   h a v e   t o   a d m i t   I   l i k e   i t   t o o .     W e   p u r c h a s e d   t h e   s t r e a m   s o   w e   c a n   l o a d   o n   w h a t e v e r   w e   l i k e   t o   p l a y   w h e n   w e   w a n t   t o .",
  'rating': 5,
  'asin': 'B00QGKWI08',
  'parent_asin': 'B00QGKWI08'},
 {'description': 'Loved this kid-friendly movie W e   l o v e d   t h i s   m o v i e   a s   a   f a m i l y .     F u n n y ,   w i t h o u t   a l l   o f   t h e   c r u d e   h u m o r   t h a t   t e n d s   t o   g o   o n   w i t h   e v e n   & # 3 4 ; k i d - f r i e n d l y & # 3 4 ;   m o v i e s .     O n e   o f   o u r   f a v e s   f o r   s u r e !',
  'rating': 5,
  'asin': 'B00ENYKO82',
  'parent_asin': 'B00ENYKO82'},
 {'description': 'A must-see! S p e c t a c u l a r   a n d   m o v i n g .   T h i s   o n c e   a g a i n   p r o v e s   P i x a r   c a n   m a k e   g r e a t   m o v i e s .   C o m p l e x   i d e a s   a r e   p r e s e n t e d   i n   a   w a y   t h a t   m i g h t   n o t   g e t   l o s t   o n   k i d s ;   i m p r e s s i v e   b y   a l l   s t a n d a r d s .   M a k e s   y o u   t h i n k   a b o u t   h o w   w e   t h i n k   a n d   i n t e r n a l l y   m a n a g e   o u r   e m o t i o n s .   E x p l o r e s   t h e   m a t u r i n g   p r o c e s s   i n   a   w a y   t h a t   w i l l   c h a n g e   h o w   y o u   t h i n k   a b o u t   i t ,   a n d   n o t   j u s t   a t   f a c e   v a l u e .',
  'rating': 5,
  'asin': 'B00ZZMERJS',
  'parent_asin': 'B00ZZMERJS'},
 {'description': 'great movie. I like how the movie was presented ... g r e a t   m o v i e . I   l i k e   h o w   t h e   m o v i e   w a s   p r e s e n t e d   w i t h   s h o w i n g   t h e   p i l o t   a f t e r   t h e   c r a s h   t h e n   e x p l a i n i n g   t h e   s t o r y .',
  'rating': 5,
  'asin': 'B01LW32XQV',
  'parent_asin': 'B01LW32XQV'},
 {'description': "Great film. I ' v e   a l w a y s   l o v e d   t h i s   f i l m .   I t ' s   g r e a t   t o   b e   a b l e   t o   w a t c h   i t   w h e n   I   l i k e .",
  'rating': 5,
  'asin': 'B0091WNNDY',
  'parent_asin': 'B0091WNNDY'},
 {'description': 'Five Stars M y   g r a n d d a u g h t e r   l o v e s   t h i s   m o v i e',
  'rating': 5,
  'asin': 'B00ZHWD78I',
  'parent_asin': 'B00ZHWD78I'}]

In [ ]:
pointstructs = []
for i, data in enumerate(data_to_embed_dev):
    embeding = get_embedding(data["description"])
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embeding,
            payload=data,
        )
    )

In [136]:
pointstructs

[PointStruct(id=0, vector=[-0.009013412520289421, -0.013456806540489197, -0.0641414225101471, 0.00398293836042285, 0.041256796568632126, -0.03614573925733566, 0.04252304509282112, 0.022159410640597343, 0.003381468588486314, -0.028179863467812538, 0.03573133051395416, -0.044986482709646225, -0.043282799422740936, 0.019247030839323997, -0.01816496066749096, 0.05705041065812111, 0.0289626382291317, -0.02725895307958126, 0.051939357072114944, -0.04413463920354843, 0.050650082528591156, 0.054794181138277054, -0.0471506230533123, 0.009859499521553516, 0.03810267522931099, -0.013387737795710564, -0.02647618018090725, 0.06018150597810745, 0.06068800762295723, 0.022608354687690735, -0.0002061256964225322, -0.022907651960849762, 0.018521813675761223, -0.0628521516919136, -0.01065378449857235, -0.01063076127320528, -0.016438255086541176, 0.009698339737951756, -0.0018259930657222867, -0.03715874254703522, 0.006014697253704071, 0.04144097864627838, 0.06814738363027573, -0.030873527750372887, 0.04335186630487442, -0.0072867050766944885, -0.01583966240286827, 0.007948610000312328, -0.038655221462249756, 0.036675263196229935, -0.0686538815498352, 0.036099694669246674, -0.009301196783781052, 0.07634349167346954, 0.0163461621850729, -0.03260023519396782, 0.003444781294092536, 0.01708289235830307, 0.0554388165473938, -0.04625273495912552, 0.014147489331662655, 0.012835191562771797, -0.026338042691349983, 0.006998920347541571, 0.013951795175671577, 0.003735443577170372, -0.03213977813720703, -0.021480239927768707, -0.004121074918657541, 0.007586000952869654, 0.032830461859703064, 0.011730099096894264, -0.013065419159829617, 0.06934456527233124, -0.014665501192212105, -0.006607533432543278, 0.022527774795889854, 0.040934477001428604, 0.041187725961208344, -0.02346019819378853, 0.01961539499461651, -0.01650732196867466, -0.012846702709794044, -0.013226578012108803, -0.03359021246433258, 0.025417132303118706, -0.0459073930978775, 0.021664422005414963, -0.053873270750045776, 0.015022354200482368, 0.0008403309038840234, 0.056405775249004364, -0.011568939313292503, 0.005939873401075602, -0.010884012095630169, 0.01853332668542862, -0.034442055970430374, -0.008696849457919598, -0.025048768147826195, 0.001206536777317524, 0.027696385979652405, -0.004040495026856661, 0.00556575320661068, -0.0031426073983311653, 0.08684186637401581, 0.014032375067472458, 0.031380027532577515, 0.0169677771627903, 0.02560131438076496, -0.0034188805148005486, -0.06520047038793564, -0.0035052159801125526, -0.034557171165943146, 0.023356594145298004, 0.02403576672077179, 0.017520323395729065, 0.02105431817471981, 0.0015310138696804643, -0.04931476339697838, 0.018337631598114967, -0.002889357041567564, 0.020904671400785446, -0.007361528929322958, -0.01724405027925968, -0.0008878153748810291, -0.01453887578099966, 0.03690549358725548, 0.054794181138277054, 0.030505163595080376, -0.015022354200482368, -0.06727252155542374, 0.003801634069532156, -0.0225507989525795, -0.0289626382291317, -0.008944343775510788, -0.001443239627406001, -0.05055799335241318, 0.0030879282858222723, 0.020167941227555275, 0.11815282702445984, -0.007948610000312328, -0.04475625604391098, 0.02357531152665615, 0.039944496005773544, 0.08969669044017792, 0.012570429593324661, -0.0339125320315361, -0.013640988618135452, -0.007079500239342451, -0.011655274778604507, 0.033820442855358124, 0.027489181607961655, -0.0541955903172493, 0.03881638124585152, -0.01507991086691618, -0.04102656617760658, -0.030873527750372887, -0.03326789662241936, -0.039322882890701294, 0.06133264675736427, 0.015517343766987324, -0.010435068048536777, 0.03504064679145813, 0.04807153344154358, -0.019465748220682144, 0.02282707206904888, -0.06902224570512772, 0.024933654814958572, -0.004414615221321583, -0.010550182312726974, -0.036260854452848434, -0.06529255956411362, -0.03324487432837486, -0.0017713139532133937, 0.029146820306777954, -0.02089315839111805, 0.03734292462468147, -0.03317580372095108, 0.03223187103867531, 0.04049704223871231, 0.0031080732587724924, 0.058431778103113174, -0.04038193076848984, -0.02580851875245571, 0.030850505456328392, 0.04770316928625107, -0.01869448460638523, 0.019212497398257256, -0.013238090090453625, 0.0037066652439534664, -0.0022101853974163532, 0.0426151379942894, -0.042338863015174866, 0.007459376007318497, -0.027120817452669144, -0.006141322664916515, 0.006423351354897022, 0.04517066478729248, -0.0011691247345879674, -0.006388817448168993, -0.011309932917356491, -0.0011230792151764035, -0.0032174314837902784, -0.04616064205765724, -0.044986482709646225, -0.007194614037871361, -0.02100827358663082, 0.04001356661319733, -0.01633465103805065, 0.004247700329869986, 0.04141795262694359, -0.004759956616908312, 0.012651009485125542, -0.01915493980050087, -0.012006372213363647, -0.025348063558340073, -0.010912790894508362, 0.0732123926281929, -0.012086951173841953, 0.027281977236270905, -0.008391797542572021, 0.014055398292839527, 0.02990657091140747, -0.004092296585440636, -0.027074771001935005, 0.031909551471471786, 0.047012485563755035, -0.06142473593354225, -0.049452900886535645, 0.07265984266996384, 0.029768435284495354, -0.0016648336313664913, 0.0036721311043947935, 0.023322060704231262, -0.04390441253781319, 0.01235171314328909, -0.022493241354823112, -0.046183668076992035, 0.0009122770861722529, -0.03048214130103588, 0.01704835705459118, 0.007407574448734522, 0.043697208166122437, -0.0028936737217009068, -0.03536296635866165, 0.024427153170108795, 0.014964797534048557, -0.004495194647461176, 0.020075850188732147, 0.03317580372095108, 0.011994860135018826, -0.005384448915719986, -0.0136524997651577, -0.02762731723487377, -0.015782104805111885, -0.005252068396657705, 0.05138681083917618, 0.005263579543679953, 0.006803227122873068, -0.023218458518385887, -0.011350222863256931, 0.026936635375022888, -0.016277095302939415, 0.009312708862125874, -0.005698134191334248, -0.00831697415560484, -0.020732000470161438, 0.014573410153388977, 0.03510971739888191, -0.01125237625092268, -0.06607533246278763, -0.031702347099781036, 0.03370532765984535, 0.030919574201107025, -0.055162545293569565, -0.022147899493575096, 0.006878050975501537, -0.04104958847165108, 0.07091011852025986, 0.029307980090379715, -0.010366000235080719, -0.08366473019123077, 0.0009216300677508116, -0.01687568612396717, 0.00798314344137907, 0.014746081084012985, 0.004532606806606054, 0.005859293509274721, 0.03568528592586517, -0.005695256404578686, -0.08113222569227219, -0.03110375627875328, 0.00020918340305797756, -0.03734292462468147, -0.058477822691202164, 0.011327200569212437, -0.03902358561754227, 0.02043270319700241, 0.01046384684741497, 0.04450300335884094, 0.03036702610552311, -0.021526284515857697, -0.007257926743477583, 0.013871216215193272, -0.005657844711095095, 0.026130838319659233, -0.029676344245672226, -0.030804459005594254, 0.006170100998133421, 0.006521197967231274, 0.012616475112736225, 0.02481854148209095, 0.02700570411980152, 0.017174983397126198, 0.0047052777372300625, -0.019972248002886772, 0.014469807967543602, 0.0045959195122122765, -0.02626897394657135, -0.05778713896870613, -0.04365116357803345, -0.02721290849149227, 0.023966697975993156, 0.015943264588713646, -0.014987819828093052, 0.021779535338282585, 0.025348063558340073, 0.014723057858645916, 0.01476910337805748, -0.013836681842803955, -0.04045099765062332, -0.028271954506635666, 0.02084711380302906, 0.01609291322529316, -0.029100775718688965, -0.05829364061355591, -0.02518690563738346, -0.02263137884438038, 0.007298216689378023, -0.028156841173768044, -0.04890035092830658, -0.030919574201107025, 0.017071379348635674, 0.0018216762691736221, -0.02523295022547245, -0.012363225221633911, 0.009145793505012989, -0.02387460693717003, -0.004961405880749226, 0.0015641091158613563, -0.021192455664277077, -0.010273909196257591, -0.027328021824359894, -0.03165630251169205, 0.011649519205093384, -0.01127539947628975, -0.015505832619965076, 0.006256436463445425, -0.006273703649640083, 0.04210863634943962, -0.001834626542404294, -0.010958836413919926, -0.022562310099601746, -0.00021439949341583997, 0.020029805600643158, 0.006083765532821417, 0.02912379801273346, 0.0014194973045960069, 0.0027857546228915453, 0.05663600191473961, 0.013307157903909683, -0.00986525509506464, -0.006768692750483751, 0.019580861553549767, -0.008679582737386227, -0.024634357541799545, -0.011845212429761887, -0.013617965392768383, -0.02076653391122818, 0.014469807967543602, 0.008426331914961338, 0.04049704223871231, 0.0013317230623215437, -0.004279356449842453, 0.03239303082227707, -0.02845613658428192, 0.015264092944562435, -5.8726036513689905e-05, -0.009853743016719818, -0.008938588201999664, 0.07367284595966339, -0.017474278807640076, -0.03768826648592949, 0.05603741109371185, 0.0005539853009395301, 0.005554242059588432, 0.009565958753228188, 0.03428089618682861, -0.018418211489915848, 0.014274113811552525, -0.016277095302939415, -0.00922637339681387, -0.01907435990869999, 0.05299840494990349, 0.016679992899298668, 0.016564879566431046, 0.011056683026254177, 0.027604294940829277, 0.009364509955048561, 0.049498945474624634, 0.0013331619556993246, 0.026499202474951744, 0.03243907541036606, -0.0047426894307136536, 0.016069889068603516, 0.0011540161212906241, -0.04459509626030922, -0.005657844711095095, -0.011016393080353737, -0.011137262918055058, -0.026798497885465622, -0.014354693703353405, -0.02965332195162773, 0.04070424661040306, -0.0273049995303154, 0.0318635068833828, 0.0773564875125885, -0.0036750088911503553, -0.04035890847444534, -0.06054987013339996, -0.03550110384821892, 0.043374888598918915, -0.009876766242086887, 0.03492553532123566, 0.0299986619502306, -0.010705585591495037, -0.010987614281475544, 0.022205457091331482, 0.058477822691202164, -0.026130838319659233, -0.03835592791438103, 0.019742021337151527, 0.034557171165943146, -0.03978333622217178, -0.004417493008077145, -0.0010504137026146054, 0.018844133242964745, -0.026683384552598, -0.016679992899298668, -0.01874053105711937, -0.02121547795832157, -0.00876591820269823, -0.027028726413846016, -0.03966822475194931, 0.028686365112662315, 0.019718999043107033, -0.03213977813720703, -0.011879746802151203, -0.01371005643159151, -0.06464792042970657, -0.00640032859519124, 0.01127539947628975, 0.0032087978906929493, -0.038655221462249756, 0.029469139873981476, 0.019995272159576416, 0.013076930306851864, -0.04277629777789116, -0.03032098151743412, -0.0488082617521286, 0.043697208166122437, -0.016035355627536774, 0.06054987013339996, 0.0318404845893383, -0.012225087732076645, -0.01282368041574955, 0.033774394541978836, 0.001712318160571158, 0.0029728144872933626, -0.039530087262392044, 0.006262192036956549, 0.03715874254703522, -0.014573410153388977, 0.0500514917075634, -0.028594274073839188, -0.06506233662366867, 0.017980778589844704, -0.08104012906551361, -0.037296880036592484, 0.004034739453345537, 0.010832211002707481, -0.02328752726316452, -0.01993771456182003, -0.008944343775510788, -0.040520064532756805, -0.0136524997651577, 0.005790225230157375, -0.0055945320054888725, -0.006642067804932594, -0.03748106211423874, -0.013675522059202194, 0.006734158843755722, 0.03068934567272663, 0.024749472737312317, 0.01853332668542862, 0.007275193929672241, 3.8198904803721234e-05, -0.006026208866387606, 0.0013856826117262244, 0.04203956946730614, 0.027558250352740288, -0.013848192989826202, -0.003787244902923703, 0.010222107172012329, 0.002755537163466215, 0.007298216689378023, -0.02229754813015461, 0.007096767425537109, -0.025117836892604828, -0.020662931725382805, -0.023322060704231262, 0.0010583277326077223, 0.013525874353945255, -0.0167490616440773, 0.0031023176852613688, 0.01567850261926651, -0.021572330966591835, -0.0015972043620422482, -0.02387460693717003, -0.022481730207800865, 0.005341281648725271, -0.003401613561436534, 0.01575908251106739, 0.01326111238449812, 0.014205045998096466, 0.04404255002737045, -0.012248110957443714, -0.04890035092830658, -0.008760161697864532, -0.0500514917075634, 0.013825170695781708, -0.034695304930210114, 0.022930674254894257, 0.021894648671150208, 0.008840741589665413, 0.010014902800321579, 0.0007662263815291226, 0.0025756717659533024, 0.01658790186047554, 0.005669355858117342, -0.006780204363167286, -0.004500950686633587, 0.022734981030225754, 0.0031023176852613688, -0.018924713134765625, 0.021940695121884346, -0.02424297109246254, -0.007010431960225105, 0.007718381937593222, 0.02486458607017994, 0.008363019675016403, -0.022619865834712982, -0.045930415391922, 0.0070449658669531345, 0.02266591228544712, 0.0678711086511612, 0.020455727353692055, 0.021491751074790955, -0.01282368041574955, 0.05332072451710701, -0.005991674493998289, -0.057602956891059875, 0.0004158486844971776, -0.0256473608314991, 0.007896807976067066, -0.012248110957443714, 0.04309861734509468, 5.261061596684158e-05, -0.008351507596671581, -0.00027609331300482154, -0.013825170695781708, -0.03048214130103588, -0.02643013373017311, -0.01251287292689085, 0.009767408482730389, -0.014205045998096466, -0.04169422760605812, 0.014159000478684902, -0.009565958753228188, -0.01666848175227642, -0.005059252493083477, -0.030919574201107025, -0.039944496005773544, -0.004380080848932266, -0.011494114995002747, 0.01928156614303589, -0.0244041308760643, -0.010953080840408802, -0.0009540058090351522, -0.014584921300411224, -0.020029805600643158, -0.029768435284495354, 0.017174983397126198, -0.03635294735431671, -0.00753995543345809, 0.031333982944488525, -0.02725895307958126, -0.04434184357523918, 0.0250257458537817, -0.017474278807640076, 0.01671452820301056, 0.0038390459958463907, 0.0541955903172493, -0.10130016505718231, -0.026545247063040733, -0.01071134116500616, -0.023644380271434784, -0.035593193024396896, 0.051478903740644455, -0.023229969665408134, -0.059628959745168686, 0.024956677109003067, 0.01662243716418743, 0.01638069748878479, 0.02295369654893875, 0.008938588201999664, -0.018222518265247345, 0.01507991086691618, -0.020490260794758797, -0.004693766124546528, 0.04761107638478279, -0.023137878626585007, 0.03462623804807663, -0.02175651304423809, -0.001000051386654377, 0.012858213856816292, -0.04058913514018059, -0.002246158430352807, -0.00456138513982296, -0.005456395447254181, 0.009957346133887768, -0.017600903287529945, -0.001667711534537375, 0.006152833811938763, -0.0013022251660004258, -0.011499871499836445, 0.0047887349501252174, -0.0036836424842476845, -0.028479160740971565, -0.009255151264369488, 0.0053096250630915165, -0.013019373640418053, 0.0397142693400383, -0.011425047181546688, 0.0012993472628295422, 0.0066823577508330345, -0.022804047912359238, -0.05907641351222992, 0.00963502749800682, -0.03810267522931099, -0.024289017543196678, 0.03306069225072861, 0.014895728789269924, -0.014861194416880608, -0.006446374114602804, -0.0033526902552694082, 0.016288606449961662, 0.0022101853974163532, 0.007004676386713982, -0.01939667947590351, -0.007332750596106052, -0.04111865907907486, -0.004129708278924227, -0.015010843053460121, -0.006647823378443718, -0.023310549557209015, 0.02105431817471981, -0.022861605510115623, -0.023552289232611656, 0.01981109008193016, -0.020536307245492935, -0.031955596059560776, -0.012846702709794044, -0.03842499479651451, 0.004613186698406935, -0.009548692032694817, 0.021641399711370468, -0.018084382638335228, 0.028686365112662315, -0.009289685636758804, -0.00686653982847929, 0.01853332668542862, 0.003211675677448511, -0.021652910858392715, 0.03209373354911804, -0.05239981412887573, 0.009531424380838871, -0.03441903367638588, 0.007868030108511448, -0.055208589881658554, -0.012179042212665081, 0.0159317534416914, -0.035385988652706146, -0.030850505456328392, -0.03483344241976738, -0.03669828549027443, -0.019638419151306152, 0.022447194904088974, 0.0026389844715595245, 0.010181818157434464, -0.0194427240639925, -0.002844750415533781, 0.022654401138424873, 0.027650341391563416, 0.024265993386507034, -0.028571251779794693, -0.009738629683852196, -0.016277095302939415, 0.003223187057301402, -0.005718279164284468, -0.030597254633903503, 0.018544837832450867, -0.013145999051630497, 0.010607738979160786, 0.015252581797540188, 0.008104013279080391, -0.00015531372628174722, -0.0210888534784317, -0.04408859461545944, 0.006872295401990414, 0.012478338554501534, 0.05055799335241318, -0.023690424859523773, -0.0033958577550947666, -0.008800451643764973, -0.014861194416880608, -0.04270722717046738, -0.03068934567272663, 0.007804717402905226, 0.0037958782631903887, -0.00034803946618922055, 0.005093786865472794, -0.012075440026819706, -0.00040433730464428663, 0.025417132303118706, -0.006193123757839203, 0.05115658417344093, 0.004624697845429182, -0.03842499479651451, -0.035800401121377945, -0.011027904227375984, 0.008397553116083145, 0.009485378861427307, -0.0007957243360579014, -0.03347510099411011, -0.028686365112662315, 0.011223597452044487, 0.011148774065077305, -0.01749730110168457, 0.00042736006435006857, -0.006003186106681824, 0.0031771415378898382, -0.003778611309826374, 0.01547129824757576, 0.010003391653299332, -0.009755896404385567, -0.0055887759663164616, -0.031909551471471786, 0.004357058089226484, -0.053550951182842255, -0.006457885727286339, -0.004362814128398895, 0.015701524913311005, -0.03057423233985901, 0.05276817828416824, -0.04843989759683609, -0.02850218303501606, 0.006049231626093388, 0.02304578758776188, 0.0019641297403723, -0.002499409019947052, -0.008702605031430721, 0.0060722543857991695, -0.009669560939073563, 0.00473693385720253, 0.018395189195871353, -0.01679510623216629, -0.012144508771598339, -0.04443393647670746, -0.01654185727238655, 0.01567850261926651, -0.0022619867231696844, -0.006348527502268553, -0.026245951652526855, 0.002781437709927559, -0.008282439783215523, 0.021975228562951088, -0.059675008058547974, -0.024795517325401306, 0.0628981962800026, 0.0200643390417099, -0.030297959223389626, 0.023471709340810776, -0.028410091996192932, 0.03193257376551628, -0.0031167068518698215, 0.0062276581302285194, 0.006135566625744104, 0.03851708397269249, -0.018049847334623337, 0.02100827358663082, -0.013882727362215519, 0.003203042084351182, 0.021031295880675316, -0.007758671883493662, -0.04843989759683609, -0.02237812802195549, 0.03338300809264183, 0.0007234184304252267, 0.03437298908829689, -0.017232539132237434, 0.011758876964449883, 0.01741672120988369, -0.008155814372003078, -0.014101443812251091, 0.015218047425150871, 0.01319204457104206, 0.0026159617118537426, -0.03326789662241936, -0.017854154109954834, -0.0033383008558303118, 0.01065378449857235, -0.011223597452044487, -0.009986124001443386, 0.014792126603424549, -0.005416105501353741, 0.00860475841909647, 0.01845274679362774, -0.008921321481466293, 0.015828151255846024, -0.018924713134765625, 0.019097384065389633, -0.03414275869727135, -0.004806002136319876, -0.0171634703874588, 0.012236599810421467, 0.00015666271792724729, 0.0002120612480212003, -0.02912379801273346, 0.0029267689678817987, 0.006970142014324665, 0.023183925077319145, 0.002292203949764371, -0.024887608364224434, -0.00758024537935853, -0.0025425765197724104, -0.031495142728090286, -0.015298627316951752, -0.005899583455175161, 0.04381232336163521, -0.010935813188552856, 0.0010424995562061667, -0.00943357776850462, 0.016645459458231926, 0.008708360604941845, 0.024887608364224434, -0.010291175916790962, -0.0030562719330191612, -0.03078143671154976, -0.02767336368560791, 0.0014691401738673449, -0.001935351174324751, 0.01575908251106739, 0.011948814615607262, 0.022401150315999985, -0.026775475591421127, 0.03665224090218544, -0.01422806829214096, 0.03962218016386032, 0.013330181129276752, 0.020743511617183685, -0.03197862207889557, 0.020536307245492935, -0.004224677570164204, -0.004526851233094931, -0.03285348415374756, 0.03713572025299072, -0.01003216952085495, -0.010751631110906601, -0.017025334760546684, -0.022746492177248, -0.026176882907748222, -0.008017677813768387, 0.01861390471458435, -0.01191428117454052, 0.025094814598560333, -0.00777593906968832, 0.0690682977437973,

Wtite embedded data to quadrant client

In [135]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-00",
    wait=True,
    points=pointstructs,
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

Define query embedding function

In [ ]:
def retrieve_data(query, k=5):
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-00",
        query=query_embedding,
        limit=k,
    )
    return results

retrieved_context = retrieve_data("What kind of earphones can I get?", qdrant_client, k=10)

In [142]:
retrieve_data("what movies are recommended for children?").points

[ScoredPoint(id=4, version=1, score=0.50967324, payload={'description': 'Loved this kid-friendly movie W e   l o v e d   t h i s   m o v i e   a s   a   f a m i l y .     F u n n y ,   w i t h o u t   a l l   o f   t h e   c r u d e   h u m o r   t h a t   t e n d s   t o   g o   o n   w i t h   e v e n   & # 3 4 ; k i d - f r i e n d l y & # 3 4 ;   m o v i e s .     O n e   o f   o u r   f a v e s   f o r   s u r e !', 'rating': 5, 'asin': 'B00ENYKO82', 'parent_asin': 'B00ENYKO82'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=6, version=1, score=0.28082705, payload={'description': 'great movie. I like how the movie was presented ... g r e a t   m o v i e . I   l i k e   h o w   t h e   m o v i e   w a s   p r e s e n t e d   w i t h   s h o w i n g   t h e   p i l o t   a f t e r   t h e   c r a s h   t h e n   e x p l a i n i n g   t h e   s t o r y .', 'rating': 5, 'asin': 'B01LW32XQV', 'parent_asin': 'B01LW32XQV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=1, score=0.26758483, payload={'description': "I'm a sucker for these sappy movies I   l i k e   a n y   m o v i e   H i l a r i e   B u r t o n   i s   i n ,   I   r e a l l y   l i k e   h e r .   T h i s   m o v i e   i s   l i k e   m o s t     H a l l m a r k   m o v i e s   a n d   t h e y   a r e   m y   g u i l t y   p l e a s u r e .   I   l i k e d   s e e i n g   a l l   t h e   f o o d   i n   t h e   m o v i e   a n d   l o v e   h o w   t h e   c h a r a c t e r s   c o m e   t o g e t h e r .   I ' v e   w a t c h e d   t h i s   m o v i e   s e v e r a l   t i m e s   a n d   I   a m   s u r e   I ' l l   w a t c h   i t   s e v e r a l   m o r e .   I   l i k e   m o v i e s   t h a t   h a v e   h a p p y   e n d i n g s   a n d   H a l l m a r k   c e r t a i n l y   i s   t h e   p l a c e   t o   g o   f o r   t h a t .", 'rating': 5, 'asin': 'B07FN83ZK1', 'parent_asin': 'B07FN83ZK1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5, version=1, score=0.25611565, payload={'description': 'A must-see! S p e c t a c u l a r   a n d   m o v i n g .   T h i s   o n c e   a g a i n   p r o v e s   P i x a r   c a n   m a k e   g r e a t   m o v i e s .   C o m p l e x   i d e a s   a r e   p r e s e n t e d   i n   a   w a y   t h a t   m i g h t   n o t   g e t   l o s t   o n   k i d s ;   i m p r e s s i v e   b y   a l l   s t a n d a r d s .   M a k e s   y o u   t h i n k   a b o u t   h o w   w e   t h i n k   a n d   i n t e r n a l l y   m a n a g e   o u r   e m o t i o n s .   E x p l o r e s   t h e   m a t u r i n g   p r o c e s s   i n   a   w a y   t h a t   w i l l   c h a n g e   h o w   y o u   t h i n k   a b o u t   i t ,   a n d   n o t   j u s t   a t   f a c e   v a l u e .', 'rating': 5, 'asin': 'B00ZZMERJS', 'parent_asin': 'B00ZZMERJS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=1, score=0.24809033, payload={'description': "Great film. I ' v e   a l w a y s   l o v e d   t h i s   f i l m .   I t ' s   g r e a t   t o   b e   a b l e   t o   w a t c h   i t   w h e n   I   l i k e .", 'rating': 5, 'asin': 'B0091WNNDY', 'parent_asin': 'B0091WNNDY'}, vector=None, shard_key=None, order_value=None)]